package com.ylzInfo.mapping;

import com.ylzInfo.bean.Appsetup;

public interface AppsetupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appsetup
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appsetup
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    int insert(Appsetup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appsetup
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    int insertSelective(Appsetup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appsetup
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    Appsetup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appsetup
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    int updateByPrimaryKeySelective(Appsetup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appsetup
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    int updateByPrimaryKey(Appsetup record);
}