package com.ylzInfo.mapping;

import com.ylzInfo.bean.Bank;

import java.util.List;

public interface BankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_bank
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_bank
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    int insert(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_bank
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    int insertSelective(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_bank
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    Bank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_bank
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    int updateByPrimaryKeySelective(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_bank
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    int updateByPrimaryKey(Bank record);

    List<Bank> selectAll();
}