package com.ylzInfo.mapping;

import com.ylzInfo.bean.Exchange;

import java.util.HashMap;
import java.util.List;

public interface ExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    int insert(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    int insertSelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    Exchange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    int updateByPrimaryKeySelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    int updateByPrimaryKey(Exchange record);
    List <Exchange> selectByUseridAndType(HashMap map);
}