package com.ylzInfo.mapping;

import com.ylzInfo.bean.Grade;

import java.util.List;

public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    int insertSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    Grade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    int updateByPrimaryKeySelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    int updateByPrimaryKey(Grade record);

    List<Grade> selectAll();
}
