package com.ylzInfo.mapping;

import com.ylzInfo.bean.User;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    int updateByPrimaryKey(User record);

    List selectByUserNameAndpwd(@Param("username") String username, @Param("password") String password);

    List selectByinvitatocode(@Param("invitationcode") String invitationcode);

    List<User> selectByAccount(@Param("username")String username);

    void changePwd(HashMap map);
}
