package com.ylzInfo.mapping;

import com.ylzInfo.bean.Withdrawal;

import java.util.HashMap;
import java.util.List;

public interface WithdrawalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawal
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawal
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    int insert(Withdrawal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawal
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    int insertSelective(Withdrawal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawal
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    Withdrawal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawal
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    int updateByPrimaryKeySelective(Withdrawal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawal
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    int updateByPrimaryKey(Withdrawal record);

    List<Withdrawal> queryByMap(HashMap param);

    Integer selectCount();

    void changeState(HashMap map);
}