package com.ylzInfo.bean;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ID
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.BALANCE
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.BANKNAME
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.BANKCARDNO
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String bankcardno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ID
     *
     * @return the value of account.ID
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ID
     *
     * @param id the value for account.ID
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.BALANCE
     *
     * @return the value of account.BALANCE
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.BALANCE
     *
     * @param balance the value for account.BALANCE
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setBalance(String balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.BANKNAME
     *
     * @return the value of account.BANKNAME
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.BANKNAME
     *
     * @param bankname the value for account.BANKNAME
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.BANKCARDNO
     *
     * @return the value of account.BANKCARDNO
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getBankcardno() {
        return bankcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.BANKCARDNO
     *
     * @param bankcardno the value for account.BANKCARDNO
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setBankcardno(String bankcardno) {
        this.bankcardno = bankcardno;
    }
}
