package com.ylzInfo.bean;

public class Appsetup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appsetup.id
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appsetup.integral
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    private String integral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appsetup.id
     *
     * @return the value of appsetup.id
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appsetup.id
     *
     * @param id the value for appsetup.id
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appsetup.integral
     *
     * @return the value of appsetup.integral
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    public String getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appsetup.integral
     *
     * @param integral the value for appsetup.integral
     *
     * @mbggenerated Fri Jul 03 09:18:51 CST 2020
     */
    public void setIntegral(String integral) {
        this.integral = integral;
    }
}