package com.ylzInfo.bean;

public class Bank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_bank.id
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_bank.bankname
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    private String bankname;

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    private String time;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_bank.bankcno
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    private String bankcno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_bank.name
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_bank.money
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_bank.level
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_bank.id
     *
     * @return the value of w_bank.id
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_bank.id
     *
     * @param id the value for w_bank.id
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_bank.bankname
     *
     * @return the value of w_bank.bankname
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_bank.bankname
     *
     * @param bankname the value for w_bank.bankname
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_bank.bankcno
     *
     * @return the value of w_bank.bankcno
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public String getBankcno() {
        return bankcno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_bank.bankcno
     *
     * @param bankcno the value for w_bank.bankcno
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public void setBankcno(String bankcno) {
        this.bankcno = bankcno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_bank.name
     *
     * @return the value of w_bank.name
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_bank.name
     *
     * @param name the value for w_bank.name
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_bank.money
     *
     * @return the value of w_bank.money
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_bank.money
     *
     * @param money the value for w_bank.money
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_bank.level
     *
     * @return the value of w_bank.level
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_bank.level
     *
     * @param level the value for w_bank.level
     *
     * @mbggenerated Thu Jul 02 15:24:05 CST 2020
     */
    public void setLevel(String level) {
        this.level = level;
    }
}
