package com.ylzInfo.bean;

public class Exchange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange.id
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange.userid
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange.type
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange.value
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange.createtime
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange.id
     *
     * @return the value of exchange.id
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange.id
     *
     * @param id the value for exchange.id
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange.userid
     *
     * @return the value of exchange.userid
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange.userid
     *
     * @param userid the value for exchange.userid
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange.type
     *
     * @return the value of exchange.type
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange.type
     *
     * @param type the value for exchange.type
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange.value
     *
     * @return the value of exchange.value
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange.value
     *
     * @param value the value for exchange.value
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange.createtime
     *
     * @return the value of exchange.createtime
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange.createtime
     *
     * @param createtime the value for exchange.createtime
     *
     * @mbggenerated Fri Jul 03 10:13:57 CST 2020
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }
}