package com.ylzInfo.bean;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.id
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gradename
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    private String gradename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.score
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    private String score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gradename
     *
     * @return the value of grade.gradename
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    public String getGradename() {
        return gradename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gradename
     *
     * @param gradename the value for grade.gradename
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    public void setGradename(String gradename) {
        this.gradename = gradename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.score
     *
     * @return the value of grade.score
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.score
     *
     * @param score the value for grade.score
     *
     * @mbggenerated Tue Jun 30 18:35:27 CST 2020
     */
    public void setScore(String score) {
        this.score = score;
    }
}