package com.ylzInfo.bean;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order.id
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order.ordernumber
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    private String ordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order.createdate
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order.orderstate
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    private String orderstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order.userid
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order.money
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order.beifen
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    private String beifen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order.bankcard
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    private String bankcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order.username
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order.id
     *
     * @return the value of w_order.id
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order.id
     *
     * @param id the value for w_order.id
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order.ordernumber
     *
     * @return the value of w_order.ordernumber
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order.ordernumber
     *
     * @param ordernumber the value for w_order.ordernumber
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order.createdate
     *
     * @return the value of w_order.createdate
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order.createdate
     *
     * @param createdate the value for w_order.createdate
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order.orderstate
     *
     * @return the value of w_order.orderstate
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public String getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order.orderstate
     *
     * @param orderstate the value for w_order.orderstate
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public void setOrderstate(String orderstate) {
        this.orderstate = orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order.userid
     *
     * @return the value of w_order.userid
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order.userid
     *
     * @param userid the value for w_order.userid
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order.money
     *
     * @return the value of w_order.money
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order.money
     *
     * @param money the value for w_order.money
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order.beifen
     *
     * @return the value of w_order.beifen
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public String getBeifen() {
        return beifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order.beifen
     *
     * @param beifen the value for w_order.beifen
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public void setBeifen(String beifen) {
        this.beifen = beifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order.bankcard
     *
     * @return the value of w_order.bankcard
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public String getBankcard() {
        return bankcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order.bankcard
     *
     * @param bankcard the value for w_order.bankcard
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public void setBankcard(String bankcard) {
        this.bankcard = bankcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order.username
     *
     * @return the value of w_order.username
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order.username
     *
     * @param username the value for w_order.username
     *
     * @mbggenerated Wed Jul 01 17:25:18 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }
}