package com.ylzInfo.bean;

public class Token {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.id
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.userid
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.createtime
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.status
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.id
     *
     * @return the value of token.id
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.id
     *
     * @param id the value for token.id
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.userid
     *
     * @return the value of token.userid
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.userid
     *
     * @param userid the value for token.userid
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token
     *
     * @return the value of token.token
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token
     *
     * @param token the value for token.token
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.createtime
     *
     * @return the value of token.createtime
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.createtime
     *
     * @param createtime the value for token.createtime
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.status
     *
     * @return the value of token.status
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.status
     *
     * @param status the value for token.status
     *
     * @mbggenerated Thu Jul 02 11:32:31 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}