package com.ylzInfo.bean;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USERNAME
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IMGURL
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SEX
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TELEPHONE
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ACCOUNT
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SIGN
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ACCOUNTID
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    private String accountid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USERNAME
     *
     * @return the value of user.USERNAME
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USERNAME
     *
     * @param username the value for user.USERNAME
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IMGURL
     *
     * @return the value of user.IMGURL
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IMGURL
     *
     * @param imgurl the value for user.IMGURL
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SEX
     *
     * @return the value of user.SEX
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SEX
     *
     * @param sex the value for user.SEX
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TELEPHONE
     *
     * @return the value of user.TELEPHONE
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TELEPHONE
     *
     * @param telephone the value for user.TELEPHONE
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ACCOUNT
     *
     * @return the value of user.ACCOUNT
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ACCOUNT
     *
     * @param account the value for user.ACCOUNT
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SIGN
     *
     * @return the value of user.SIGN
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SIGN
     *
     * @param sign the value for user.SIGN
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ACCOUNTID
     *
     * @return the value of user.ACCOUNTID
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ACCOUNTID
     *
     * @param accountid the value for user.ACCOUNTID
     *
     * @mbggenerated Thu Mar 19 10:40:05 CST 2020
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }
}
