package com.ylzInfo.bean;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.id
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.username
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.password
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.invitationcode
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    private String invitationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.balance
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    private String balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.id
     *
     * @return the value of w_user.id
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.id
     *
     * @param id the value for w_user.id
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.username
     *
     * @return the value of w_user.username
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.username
     *
     * @param username the value for w_user.username
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.password
     *
     * @return the value of w_user.password
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.password
     *
     * @param password the value for w_user.password
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.invitationcode
     *
     * @return the value of w_user.invitationcode
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public String getInvitationcode() {
        return invitationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.invitationcode
     *
     * @param invitationcode the value for w_user.invitationcode
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public void setInvitationcode(String invitationcode) {
        this.invitationcode = invitationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.balance
     *
     * @return the value of w_user.balance
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.balance
     *
     * @param balance the value for w_user.balance
     *
     * @mbggenerated Mon Jun 29 20:53:30 CST 2020
     */
    public void setBalance(String balance) {
        this.balance = balance;
    }
}