package com.ylzInfo.bean;

public class Withdrawal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.id
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.realname
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.bankno
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private String bankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.money
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.password
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.state
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.beiliu
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private String beiliu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.createtime
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.userid
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.bankname
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal.username
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.id
     *
     * @return the value of withdrawal.id
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.id
     *
     * @param id the value for withdrawal.id
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.realname
     *
     * @return the value of withdrawal.realname
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.realname
     *
     * @param realname the value for withdrawal.realname
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.bankno
     *
     * @return the value of withdrawal.bankno
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.bankno
     *
     * @param bankno the value for withdrawal.bankno
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setBankno(String bankno) {
        this.bankno = bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.money
     *
     * @return the value of withdrawal.money
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.money
     *
     * @param money the value for withdrawal.money
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.password
     *
     * @return the value of withdrawal.password
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.password
     *
     * @param password the value for withdrawal.password
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.state
     *
     * @return the value of withdrawal.state
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.state
     *
     * @param state the value for withdrawal.state
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.beiliu
     *
     * @return the value of withdrawal.beiliu
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public String getBeiliu() {
        return beiliu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.beiliu
     *
     * @param beiliu the value for withdrawal.beiliu
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setBeiliu(String beiliu) {
        this.beiliu = beiliu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.createtime
     *
     * @return the value of withdrawal.createtime
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.createtime
     *
     * @param createtime the value for withdrawal.createtime
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.userid
     *
     * @return the value of withdrawal.userid
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.userid
     *
     * @param userid the value for withdrawal.userid
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.bankname
     *
     * @return the value of withdrawal.bankname
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.bankname
     *
     * @param bankname the value for withdrawal.bankname
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal.username
     *
     * @return the value of withdrawal.username
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal.username
     *
     * @param username the value for withdrawal.username
     *
     * @mbggenerated Fri Jul 03 14:28:44 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }
}